/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cli_rpc.h"
/* AAAAAAAAAAA */

bool_t
xdr_pthread_mutex_t(xdrs, objp)
	register XDR *xdrs;
	pthread_mutex_t	*objp;
{
#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif
	return (TRUE);
}

bool_t
xdr_IPaddr(xdrs, objp)
	register XDR *xdrs;
	IPaddr	*objp;
{
#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif
	if (!xdr_u_long(xdrs, &objp->l))
		return (FALSE);
	return (TRUE);
}


bool_t
xdr_tm(xdrs, objp)
	register XDR *xdrs;
	struct tm *objp;
{
#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif
		if (!xdr_int(xdrs, &objp->tm_sec))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->tm_min))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->tm_hour))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->tm_mday))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->tm_mon))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->tm_year))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->tm_wday))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->tm_yday))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->tm_isdst))
			return (FALSE);
		return(TRUE);
}

bool_t
xdr_time_t(xdrs, objp)
	register XDR *xdrs;
	time_t *objp;
{
#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif
	if (!xdr_long(xdrs, (long *)objp))
		return (FALSE);
	return(TRUE);
}


bool_t
xdr__cache_table_info(xdrs, objp)
	register XDR *xdrs;
	_cache_table_info *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_InfoEntry(xdrs, &objp->data))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->iserver_addr))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->state))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr__CacheRouteEntry(xdrs, objp)
	register XDR *xdrs;
	_CacheRouteEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

#if 0
	if (!xdr_int(xdrs,(int *)&objp->prev));
		return (FALSE);
	if (!xdr_int(xdrs,(int *)&objp->next));
		return (FALSE);
	if (!xdr_int(xdrs,(int *)&objp->sprev));
		return (FALSE);
	if (!xdr_int(xdrs, (int *)&objp->snext));
		return (FALSE);
	if (!xdr_int(xdrs, (int *)&objp->tprev));
		return (FALSE);
	if (!xdr_int(xdrs, (int *)&objp->tnext));
		return (FALSE);
#endif
	if (!xdr_VpnRouteEntry(xdrs, &objp->routeEntry))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->iserver_addr))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->state))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr__CacheCPBEntry(xdrs, objp)
	register XDR *xdrs;
	_CacheCPBEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

#if 0
	if (!xdr_int(xdrs,(int *)&objp->crprev));
		return (FALSE);
	if (!xdr_int(xdrs, (int *)&objp->crnext));
		return (FALSE);
	if (!xdr_int(xdrs,(int *)&objp->cpprev));
		return (FALSE);
	if (!xdr_int(xdrs, (int *)&objp->cpnext));
		return (FALSE);
#endif
	if (!xdr_CallPlanBindEntry(xdrs, &objp->cpbEntry))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->iserver_addr))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->state))
		return (FALSE);
	return (TRUE);
}
/* BBBBBBBBBBBBBB */

bool_t
xdr_Vendor_e(xdrs, objp)
	register XDR *xdrs;
	Vendor_e *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Vendor(xdrs, objp)
	register XDR *xdrs;
	Vendor *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_Vendor_e(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_info_entry(xdrs, objp)
	register XDR *xdrs;
	info_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		if (!xdr_vector(xdrs, (char *)objp->regid, REG_ID_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->uport))
			return (FALSE);
		if (!xdr_IPaddr(xdrs, &objp->ipaddress))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->phone, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->vpnName, VPNS_ATTR_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->vpnPhone, VPN_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->vpnExtLen))
			return (FALSE);
		if (!xdr_u_short(xdrs, &objp->sflags))
			return (FALSE);
		if (!xdr_u_short(xdrs, &objp->dflags))
			return (FALSE);
		if (!xdr_long(xdrs, &objp->stateFlags))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->nphone, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->nvpnPhone, VPN_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->nvpnExtLen))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->protocol))
			return (FALSE);
		if (!xdr_u_short(xdrs, &objp->nsflags))
			return (FALSE);
		if (!xdr_u_short(xdrs, &objp->ispcorgw))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->iTime))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->mTime))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->cTime))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->rTime))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->iaTime))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->attTime))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->dndTime))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->zone, ZONE_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->cpname, CALLPLAN_ATTR_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		buf = XDR_INLINE(xdrs, (6 + (PORT_ARRAY_LEN + PORT_ARRAY_LEN)) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_short(xdrs, &objp->cap))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->rasport))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->rasip))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->ports, PORT_ARRAY_LEN,
				sizeof (u_long), (xdrproc_t) xdr_u_long))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->nports))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->cfgports, PORT_ARRAY_LEN,
				sizeof (u_long), (xdrproc_t) xdr_u_long))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->ncfgports))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->callsigport))
				return (FALSE);

		} else {
#if defined(_LP64) || defined(_KERNEL)
			IXDR_PUT_U_SHORT(buf, objp->cap);
			IXDR_PUT_U_SHORT(buf, objp->rasport);
			IXDR_PUT_U_INT32(buf, objp->rasip);
			{
				register u_long *genp;

				for (i = 0, genp = objp->ports;
					i < PORT_ARRAY_LEN; i++) {
					IXDR_PUT_U_INT32(buf, *genp++);
				}
			}
			IXDR_PUT_U_SHORT(buf, objp->nports);
			{
				register u_long *genp;

				for (i = 0, genp = objp->cfgports;
					i < PORT_ARRAY_LEN; i++) {
					IXDR_PUT_U_INT32(buf, *genp++);
				}
			}
			IXDR_PUT_U_SHORT(buf, objp->ncfgports);
			IXDR_PUT_U_SHORT(buf, objp->callsigport);
#else
			IXDR_PUT_U_SHORT(buf, objp->cap);
			IXDR_PUT_U_SHORT(buf, objp->rasport);
			IXDR_PUT_U_LONG(buf, objp->rasip);
			{
				register u_long *genp;

				for (i = 0, genp = objp->ports;
					i < PORT_ARRAY_LEN; i++) {
					IXDR_PUT_U_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_U_SHORT(buf, objp->nports);
			{
				register u_long *genp;

				for (i = 0, genp = objp->cfgports;
					i < PORT_ARRAY_LEN; i++) {
					IXDR_PUT_U_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_U_SHORT(buf, objp->ncfgports);
			IXDR_PUT_U_SHORT(buf, objp->callsigport);
#endif
		}
		if (!xdr_vector(xdrs, (char *)objp->email, EMAIL_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->h323id, H323ID_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->pgkid, GKID_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->uri, SIPURL_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->contact, SIPURL_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		buf = XDR_INLINE(xdrs, 7 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_short(xdrs, &objp->ncallsIn))
				return (FALSE);
			if (!xdr_short(xdrs, &objp->ncallsOut))
				return (FALSE);
			if (!xdr_short(xdrs, &objp->ncalls))
				return (FALSE);
			if (!xdr_short(xdrs, &objp->xcalls))
				return (FALSE);
			if (!xdr_short(xdrs, &objp->xcallsIn))
				return (FALSE);
			if (!xdr_short(xdrs, &objp->xcallsOut))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->priority))
				return (FALSE);

		} else {
#if defined(_LP64) || defined(_KERNEL)
			IXDR_PUT_SHORT(buf, objp->ncallsIn);
			IXDR_PUT_SHORT(buf, objp->ncallsOut);
			IXDR_PUT_SHORT(buf, objp->ncalls);
			IXDR_PUT_SHORT(buf, objp->xcalls);
			IXDR_PUT_SHORT(buf, objp->xcallsIn);
			IXDR_PUT_SHORT(buf, objp->xcallsOut);
			IXDR_PUT_INT32(buf, objp->priority);
#else
			IXDR_PUT_SHORT(buf, objp->ncallsIn);
			IXDR_PUT_SHORT(buf, objp->ncallsOut);
			IXDR_PUT_SHORT(buf, objp->ncalls);
			IXDR_PUT_SHORT(buf, objp->xcalls);
			IXDR_PUT_SHORT(buf, objp->xcallsIn);
			IXDR_PUT_SHORT(buf, objp->xcallsOut);
			IXDR_PUT_LONG(buf, objp->priority);
#endif
		}
		if (!xdr_vector(xdrs, (char *)objp->techprefix, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->subnetip))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->subnetmask))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->vendor))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->passwd, PASSWD_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->maxHunts))
			return (FALSE);
		if (!xdr_u_int(xdrs, &objp->ecaps1))
			return (FALSE);
		if (!xdr_u_int(xdrs, &objp->crId))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->custID, CLIENT_ATTR_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->q931IE, Q931IE_LEN,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->bcap, BCAP_LEN,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->tg, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->srcIngressTG, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->ogprefix, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->rejectTime))
			return (FALSE);
		if (!xdr_short(xdrs, &objp->infoTransCap))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->realmName, REALM_NAME_LEN,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			return (FALSE);
		if (!xdr_u_int(xdrs, &objp->realmId))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->igrpName, IGRP_NAME_LEN,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->qval, 4,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->srcEgressTG, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->dtg, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		if (!xdr_vector(xdrs, (char *)objp->regid, REG_ID_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->uport))
			return (FALSE);
		if (!xdr_IPaddr(xdrs, &objp->ipaddress))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->phone, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->vpnName, VPNS_ATTR_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->vpnPhone, VPN_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->vpnExtLen))
			return (FALSE);
		if (!xdr_u_short(xdrs, &objp->sflags))
			return (FALSE);
		if (!xdr_u_short(xdrs, &objp->dflags))
			return (FALSE);
		if (!xdr_long(xdrs, &objp->stateFlags))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->nphone, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->nvpnPhone, VPN_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->nvpnExtLen))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->protocol))
			return (FALSE);
		if (!xdr_u_short(xdrs, &objp->nsflags))
			return (FALSE);
		if (!xdr_u_short(xdrs, &objp->ispcorgw))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->iTime))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->mTime))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->cTime))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->rTime))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->iaTime))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->attTime))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->dndTime))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->zone, ZONE_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->cpname, CALLPLAN_ATTR_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		buf = XDR_INLINE(xdrs, (6 + (PORT_ARRAY_LEN + PORT_ARRAY_LEN)) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_short(xdrs, &objp->cap))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->rasport))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->rasip))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->ports, PORT_ARRAY_LEN,
				sizeof (u_long), (xdrproc_t) xdr_u_long))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->nports))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->cfgports, PORT_ARRAY_LEN,
				sizeof (u_long), (xdrproc_t) xdr_u_long))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->ncfgports))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->callsigport))
				return (FALSE);

		} else {
#if defined(_LP64) || defined(_KERNEL)
			objp->cap = IXDR_GET_U_SHORT(buf);
			objp->rasport = IXDR_GET_U_SHORT(buf);
			objp->rasip = IXDR_GET_U_INT32(buf);
			{
				register u_long *genp;

				for (i = 0, genp = objp->ports;
					i < PORT_ARRAY_LEN; i++) {
					*genp++ = IXDR_GET_U_INT32(buf);
				}
			}
			objp->nports = IXDR_GET_U_SHORT(buf);
			{
				register u_long *genp;

				for (i = 0, genp = objp->cfgports;
					i < PORT_ARRAY_LEN; i++) {
					*genp++ = IXDR_GET_U_INT32(buf);
				}
			}
			objp->ncfgports = IXDR_GET_U_SHORT(buf);
			objp->callsigport = IXDR_GET_U_SHORT(buf);
#else
			objp->cap = IXDR_GET_U_SHORT(buf);
			objp->rasport = IXDR_GET_U_SHORT(buf);
			objp->rasip = IXDR_GET_U_LONG(buf);
			{
				register u_long *genp;

				for (i = 0, genp = objp->ports;
					i < PORT_ARRAY_LEN; i++) {
					*genp++ = IXDR_GET_U_LONG(buf);
				}
			}
			objp->nports = IXDR_GET_U_SHORT(buf);
			{
				register u_long *genp;

				for (i = 0, genp = objp->cfgports;
					i < PORT_ARRAY_LEN; i++) {
					*genp++ = IXDR_GET_U_LONG(buf);
				}
			}
			objp->ncfgports = IXDR_GET_U_SHORT(buf);
			objp->callsigport = IXDR_GET_U_SHORT(buf);
#endif
		}
		if (!xdr_vector(xdrs, (char *)objp->email, EMAIL_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->h323id, H323ID_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->pgkid, GKID_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->uri, SIPURL_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->contact, SIPURL_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		buf = XDR_INLINE(xdrs, 7 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_short(xdrs, &objp->ncallsIn))
				return (FALSE);
			if (!xdr_short(xdrs, &objp->ncallsOut))
				return (FALSE);
			if (!xdr_short(xdrs, &objp->ncalls))
				return (FALSE);
			if (!xdr_short(xdrs, &objp->xcalls))
				return (FALSE);
			if (!xdr_short(xdrs, &objp->xcallsIn))
				return (FALSE);
			if (!xdr_short(xdrs, &objp->xcallsOut))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->priority))
				return (FALSE);

		} else {
#if defined(_LP64) || defined(_KERNEL)
			objp->ncallsIn = IXDR_GET_SHORT(buf);
			objp->ncallsOut = IXDR_GET_SHORT(buf);
			objp->ncalls = IXDR_GET_SHORT(buf);
			objp->xcalls = IXDR_GET_SHORT(buf);
			objp->xcallsIn = IXDR_GET_SHORT(buf);
			objp->xcallsOut = IXDR_GET_SHORT(buf);
			objp->priority = IXDR_GET_INT32(buf);
#else
			objp->ncallsIn = IXDR_GET_SHORT(buf);
			objp->ncallsOut = IXDR_GET_SHORT(buf);
			objp->ncalls = IXDR_GET_SHORT(buf);
			objp->xcalls = IXDR_GET_SHORT(buf);
			objp->xcallsIn = IXDR_GET_SHORT(buf);
			objp->xcallsOut = IXDR_GET_SHORT(buf);
			objp->priority = IXDR_GET_LONG(buf);
#endif
		}
		if (!xdr_vector(xdrs, (char *)objp->techprefix, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->subnetip))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->subnetmask))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->vendor))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->passwd, PASSWD_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->maxHunts))
			return (FALSE);
		if (!xdr_u_int(xdrs, &objp->ecaps1))
			return (FALSE);
		if (!xdr_u_int(xdrs, &objp->crId))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->custID, CLIENT_ATTR_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->q931IE, Q931IE_LEN,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->bcap, BCAP_LEN,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->tg, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->srcIngressTG, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->ogprefix, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_time_t(xdrs, &objp->rejectTime))
			return (FALSE);
		if (!xdr_short(xdrs, &objp->infoTransCap))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->realmName, REALM_NAME_LEN,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			return (FALSE);
		if (!xdr_u_int(xdrs, &objp->realmId))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->igrpName, IGRP_NAME_LEN,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->qval, 4,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->srcEgressTG, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->dtg, PHONE_NUM_LEN,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		return (TRUE);
	}

	if (!xdr_vector(xdrs, (char *)objp->regid, REG_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->uport))
		return (FALSE);
	if (!xdr_IPaddr(xdrs, &objp->ipaddress))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->phone, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->vpnName, VPNS_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->vpnPhone, VPN_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->vpnExtLen))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->sflags))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->dflags))
		return (FALSE);
	if (!xdr_long(xdrs, &objp->stateFlags))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->nphone, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->nvpnPhone, VPN_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->nvpnExtLen))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->protocol))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->nsflags))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->ispcorgw))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->iTime))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->mTime))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->cTime))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->rTime))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->iaTime))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->attTime))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->dndTime))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->zone, ZONE_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->cpname, CALLPLAN_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->cap))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->rasport))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->rasip))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->ports, PORT_ARRAY_LEN,
		sizeof (u_long), (xdrproc_t) xdr_u_long))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->nports))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->cfgports, PORT_ARRAY_LEN,
		sizeof (u_long), (xdrproc_t) xdr_u_long))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->ncfgports))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->callsigport))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->email, EMAIL_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->h323id, H323ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->pgkid, GKID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->uri, SIPURL_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->contact, SIPURL_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_short(xdrs, &objp->ncallsIn))
		return (FALSE);
	if (!xdr_short(xdrs, &objp->ncallsOut))
		return (FALSE);
	if (!xdr_short(xdrs, &objp->ncalls))
		return (FALSE);
	if (!xdr_short(xdrs, &objp->xcalls))
		return (FALSE);
	if (!xdr_short(xdrs, &objp->xcallsIn))
		return (FALSE);
	if (!xdr_short(xdrs, &objp->xcallsOut))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->priority))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->techprefix, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->subnetip))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->subnetmask))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->vendor))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->passwd, PASSWD_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->maxHunts))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->ecaps1))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->crId))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->custID, CLIENT_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->q931IE, Q931IE_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->bcap, BCAP_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->tg, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->srcIngressTG, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->ogprefix, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->rejectTime))
		return (FALSE);
	if (!xdr_short(xdrs, &objp->infoTransCap))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->realmName, REALM_NAME_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->realmId))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->igrpName, IGRP_NAME_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->qval, 4,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->srcEgressTG, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->dtg, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_InfoEntry(xdrs, objp)
	register XDR *xdrs;
	InfoEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_info_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_NetoidInfoEntry(xdrs, objp)
	register XDR *xdrs;
	NetoidInfoEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_InfoEntry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vpn_entry(xdrs, objp)
	register XDR *xdrs;
	vpn_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->vpnName, VPNS_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->vpnId, VPN_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->vpnExtLen))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->cpname, CALLPLAN_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->prefix, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->sipdomain, SIPURL_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->nUsers))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->vpnGroup, VPN_GROUP_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->vpnLoc, VPNS_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->vpnContact, VPNS_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->mTime))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_VpnEntry(xdrs, objp)
	register XDR *xdrs;
	VpnEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_vpn_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vpn_group_entry(xdrs, objp)
	register XDR *xdrs;
	vpn_group_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->vpnGroup, VPN_GROUP_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->cpname, CALLPLAN_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->mTime))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_VpnGroupEntry(xdrs, objp)
	register XDR *xdrs;
	VpnGroupEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_vpn_group_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vpn_route_entry(xdrs, objp)
	register XDR *xdrs;
	vpn_route_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->crname, CALLPLAN_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->src, VPN_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->srclen))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->srcprefix, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->tmpsrcprefix, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->dest, VPN_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->destlen))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->prefix, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->startTime))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->endTime))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->crflags))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->mTime))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->rTime))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->cpname, CALLPLAN_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->trname, TRIGGER_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_VpnRouteEntry(xdrs, objp)
	register XDR *xdrs;
	VpnRouteEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_vpn_route_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CallPlanRouteEntry(xdrs, objp)
	register XDR *xdrs;
	CallPlanRouteEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_vpn_route_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_RouteEntry(xdrs, objp)
	register XDR *xdrs;
	RouteEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_vpn_route_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_call_plan_entry(xdrs, objp)
	register XDR *xdrs;
	call_plan_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->cpname, CALLPLAN_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->pcpname, CALLPLAN_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->vpnGroup, VPN_GROUP_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->mTime))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CallPlanEntry(xdrs, objp)
	register XDR *xdrs;
	CallPlanEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_call_plan_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_call_plan_bind_entry(xdrs, objp)
	register XDR *xdrs;
	call_plan_bind_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->cpname, CALLPLAN_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->crname, CALLPLAN_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_tm(xdrs, &objp->sTime))
		return (FALSE);
	if (!xdr_tm(xdrs, &objp->fTime))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->priority))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->crflags))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->mTime))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CallPlanBindEntry(xdrs, objp)
	register XDR *xdrs;
	CallPlanBindEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_call_plan_bind_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_trigger_entry(xdrs, objp)
	register XDR *xdrs;
	trigger_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->name, TRIGGER_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->event))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->srcvendor))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->dstvendor))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->action))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->actiondata, TRIGGER_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->actionflags))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_TriggerEntry(xdrs, objp)
	register XDR *xdrs;
	TriggerEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_trigger_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_realm_address_enum(xdrs, objp)
	register XDR *xdrs;
	realm_address_enum *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Address_e(xdrs, objp)
	register XDR *xdrs;
	Address_e *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_realm_address_enum(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_realm_entry(xdrs, objp)
	register XDR *xdrs;
	realm_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		if (!xdr_u_long(xdrs, &objp->realmId))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->realmName, REALM_NAME_LEN,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			return (FALSE);
		buf = XDR_INLINE(xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_long(xdrs, &objp->rsa))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->mask))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->sigPoolId))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->medPoolId))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->adminStatus))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->operStatus))
				return (FALSE);

		} else {
#if defined(_LP64) || defined(_KERNEL)
			IXDR_PUT_U_INT32(buf, objp->rsa);
			IXDR_PUT_U_INT32(buf, objp->mask);
			IXDR_PUT_U_INT32(buf, objp->sigPoolId);
			IXDR_PUT_U_INT32(buf, objp->medPoolId);
			IXDR_PUT_U_INT32(buf, objp->adminStatus);
			IXDR_PUT_U_INT32(buf, objp->operStatus);
#else
			IXDR_PUT_U_LONG(buf, objp->rsa);
			IXDR_PUT_U_LONG(buf, objp->mask);
			IXDR_PUT_U_LONG(buf, objp->sigPoolId);
			IXDR_PUT_U_LONG(buf, objp->medPoolId);
			IXDR_PUT_U_LONG(buf, objp->adminStatus);
			IXDR_PUT_U_LONG(buf, objp->operStatus);
#endif
		}
		if (!xdr_Address_e(xdrs, &objp->addrType))
			return (FALSE);
		if (!xdr_u_short(xdrs, &objp->interRealm_mr))
			return (FALSE);
		if (!xdr_u_short(xdrs, &objp->intraRealm_mr))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->ifName, IFI_NAME,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->vipName, IFI_NAME,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->flags))
			return (FALSE);
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		if (!xdr_u_long(xdrs, &objp->realmId))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->realmName, REALM_NAME_LEN,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			return (FALSE);
		buf = XDR_INLINE(xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_long(xdrs, &objp->rsa))
				return (FALSE);
			if (!xdr_u_long(xdrs, &objp->mask))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->sigPoolId))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->medPoolId))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->adminStatus))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->operStatus))
				return (FALSE);

		} else {
#if defined(_LP64) || defined(_KERNEL)
			objp->rsa = IXDR_GET_U_INT32(buf);
			objp->mask = IXDR_GET_U_INT32(buf);
			objp->sigPoolId = IXDR_GET_U_INT32(buf);
			objp->medPoolId = IXDR_GET_U_INT32(buf);
			objp->adminStatus = IXDR_GET_U_INT32(buf);
			objp->operStatus = IXDR_GET_U_INT32(buf);
#else
			objp->rsa = IXDR_GET_U_LONG(buf);
			objp->mask = IXDR_GET_U_LONG(buf);
			objp->sigPoolId = IXDR_GET_U_LONG(buf);
			objp->medPoolId = IXDR_GET_U_LONG(buf);
			objp->adminStatus = IXDR_GET_U_LONG(buf);
			objp->operStatus = IXDR_GET_U_LONG(buf);
#endif
		}
		if (!xdr_Address_e(xdrs, &objp->addrType))
			return (FALSE);
		if (!xdr_u_short(xdrs, &objp->interRealm_mr))
			return (FALSE);
		if (!xdr_u_short(xdrs, &objp->intraRealm_mr))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->ifName, IFI_NAME,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->vipName, IFI_NAME,
			sizeof (char), (xdrproc_t) xdr_char))
			return (FALSE);
		if (!xdr_u_long(xdrs, &objp->flags))
			return (FALSE);
		return (TRUE);
	}

	if (!xdr_u_long(xdrs, &objp->realmId))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->realmName, REALM_NAME_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->rsa))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->mask))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->sigPoolId))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->medPoolId))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->adminStatus))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->operStatus))
		return (FALSE);
	if (!xdr_Address_e(xdrs, &objp->addrType))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->interRealm_mr))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->intraRealm_mr))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->ifName, IFI_NAME,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->vipName, IFI_NAME,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->flags))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_RealmEntry(xdrs, objp)
	register XDR *xdrs;
	RealmEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_realm_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_igrp_info(xdrs, objp)
	register XDR *xdrs;
	igrp_info *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		if (!xdr_vector(xdrs, (char *)objp->igrpName, IGRP_NAME_LEN,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			return (FALSE);
		buf = XDR_INLINE(xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_short(xdrs, &objp->nMaxCallsIn))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->nMaxCallsOut))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->nMaxCallsTotal))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->nCallsIn))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->nCallsOut))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->nCallsTotal))
				return (FALSE);

		} else {
#if defined(_LP64) || defined(_KERNEL)
			IXDR_PUT_U_SHORT(buf, objp->nMaxCallsIn);
			IXDR_PUT_U_SHORT(buf, objp->nMaxCallsOut);
			IXDR_PUT_U_SHORT(buf, objp->nMaxCallsTotal);
			IXDR_PUT_U_SHORT(buf, objp->nCallsIn);
			IXDR_PUT_U_SHORT(buf, objp->nCallsOut);
			IXDR_PUT_U_SHORT(buf, objp->nCallsTotal);
#else
			IXDR_PUT_U_SHORT(buf, objp->nMaxCallsIn);
			IXDR_PUT_U_SHORT(buf, objp->nMaxCallsOut);
			IXDR_PUT_U_SHORT(buf, objp->nMaxCallsTotal);
			IXDR_PUT_U_SHORT(buf, objp->nCallsIn);
			IXDR_PUT_U_SHORT(buf, objp->nCallsOut);
			IXDR_PUT_U_SHORT(buf, objp->nCallsTotal);
#endif
		}
		if (!xdr_time_t(xdrs, &objp->dndTime))
			return (FALSE);
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		if (!xdr_vector(xdrs, (char *)objp->igrpName, IGRP_NAME_LEN,
			sizeof (u_char), (xdrproc_t) xdr_u_char))
			return (FALSE);
		buf = XDR_INLINE(xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_short(xdrs, &objp->nMaxCallsIn))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->nMaxCallsOut))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->nMaxCallsTotal))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->nCallsIn))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->nCallsOut))
				return (FALSE);
			if (!xdr_u_short(xdrs, &objp->nCallsTotal))
				return (FALSE);

		} else {
#if defined(_LP64) || defined(_KERNEL)
			objp->nMaxCallsIn = IXDR_GET_U_SHORT(buf);
			objp->nMaxCallsOut = IXDR_GET_U_SHORT(buf);
			objp->nMaxCallsTotal = IXDR_GET_U_SHORT(buf);
			objp->nCallsIn = IXDR_GET_U_SHORT(buf);
			objp->nCallsOut = IXDR_GET_U_SHORT(buf);
			objp->nCallsTotal = IXDR_GET_U_SHORT(buf);
#else
			objp->nMaxCallsIn = IXDR_GET_U_SHORT(buf);
			objp->nMaxCallsOut = IXDR_GET_U_SHORT(buf);
			objp->nMaxCallsTotal = IXDR_GET_U_SHORT(buf);
			objp->nCallsIn = IXDR_GET_U_SHORT(buf);
			objp->nCallsOut = IXDR_GET_U_SHORT(buf);
			objp->nCallsTotal = IXDR_GET_U_SHORT(buf);
#endif
		}
		if (!xdr_time_t(xdrs, &objp->dndTime))
			return (FALSE);
		return (TRUE);
	}

	if (!xdr_vector(xdrs, (char *)objp->igrpName, IGRP_NAME_LEN,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->nMaxCallsIn))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->nMaxCallsOut))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->nMaxCallsTotal))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->nCallsIn))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->nCallsOut))
		return (FALSE);
	if (!xdr_u_short(xdrs, &objp->nCallsTotal))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->dndTime))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_IgrpInfo(xdrs, objp)
	register XDR *xdrs;
	IgrpInfo *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_igrp_info(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheTableInfo(xdrs, objp)
	register XDR *xdrs;
	CacheTableInfo *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr__cache_table_info(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cache_table_entry(xdrs, objp)
	register XDR *xdrs;
	cache_table_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_pointer(xdrs, (char **)&objp->info, sizeof (CacheTableInfo), (xdrproc_t) xdr_CacheTableInfo))
		return (FALSE);
	if (!xdr_long(xdrs, &objp->index))
		return (FALSE);
	if (!xdr_long(xdrs, &objp->numInfo))
		return (FALSE);
	if (!xdr_pthread_mutex_t(xdrs, &objp->mutex))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheTableEntry(xdrs, objp)
	register XDR *xdrs;
	CacheTableEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_cache_table_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cache_vpn_entry(xdrs, objp)
	register XDR *xdrs;
	cache_vpn_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_VpnEntry(xdrs, &objp->vpnEntry))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->iserver_addr))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->state))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheVpnEntry(xdrs, objp)
	register XDR *xdrs;
	CacheVpnEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_cache_vpn_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cache_vpng_entry(xdrs, objp)
	register XDR *xdrs;
	cache_vpng_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_VpnGroupEntry(xdrs, &objp->vpnGroupEntry))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->iserver_addr))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->state))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheVpnGEntry(xdrs, objp)
	register XDR *xdrs;
	CacheVpnGEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_cache_vpng_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cache_cp_entry(xdrs, objp)
	register XDR *xdrs;
	cache_cp_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_CallPlanEntry(xdrs, &objp->cpEntry))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->iserver_addr))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->state))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheCPEntry(xdrs, objp)
	register XDR *xdrs;
	CacheCPEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_cache_cp_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}


bool_t
xdr_CacheVpnRouteEntry(xdrs, objp)
	register XDR *xdrs;
	CacheVpnRouteEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr__CacheRouteEntry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheRouteEntry(xdrs, objp)
	register XDR *xdrs;
	CacheRouteEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr__CacheRouteEntry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}


bool_t
xdr_CacheCPBEntry(xdrs, objp)
	register XDR *xdrs;
	CacheCPBEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr__CacheCPBEntry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cache_trigger_entry(xdrs, objp)
	register XDR *xdrs;
	cache_trigger_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_TriggerEntry(xdrs, &objp->trigger))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->ntriggers))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheTriggerEntry(xdrs, objp)
	register XDR *xdrs;
	CacheTriggerEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_cache_trigger_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cache_realm_entry(xdrs, objp)
	register XDR *xdrs;
	cache_realm_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_RealmEntry(xdrs, &objp->realm))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->socketId))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheRealmEntry(xdrs, objp)
	register XDR *xdrs;
	CacheRealmEntry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_cache_realm_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cache_igrp_info(xdrs, objp)
	register XDR *xdrs;
	cache_igrp_info *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_IgrpInfo(xdrs, &objp->igrp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheIgrpInfo(xdrs, objp)
	register XDR *xdrs;
	CacheIgrpInfo *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_cache_igrp_info(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gk_info(xdrs, objp)
	register XDR *xdrs;
	gk_info *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->regid, REG_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->uport))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->regttl))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->endpointIDString, ENDPOINTID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->endpointIDLen))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->gkIDString, GKID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->regState))
		return (FALSE);
	if (!xdr_time_t(xdrs, &objp->nextEvent))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->crId))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->flags))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_GkInfo(xdrs, objp)
	register XDR *xdrs;
	GkInfo *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_gk_info(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheGkInfo(xdrs, objp)
	register XDR *xdrs;
	CacheGkInfo *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_gk_info(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_netoid_snkey(xdrs, objp)
	register XDR *xdrs;
	netoid_snkey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->regid, REG_ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->uport))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_NetoidSNKey(xdrs, objp)
	register XDR *xdrs;
	NetoidSNKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_netoid_snkey(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_netoid_phone_key(xdrs, objp)
	register XDR *xdrs;
	netoid_phone_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->phone, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_NetoidPhoneKey(xdrs, objp)
	register XDR *xdrs;
	NetoidPhoneKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_netoid_phone_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_netoid_email_key(xdrs, objp)
	register XDR *xdrs;
	netoid_email_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->email, EMAIL_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_NetoidEmailKey(xdrs, objp)
	register XDR *xdrs;
	NetoidEmailKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_netoid_email_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_netoid_h323id_key(xdrs, objp)
	register XDR *xdrs;
	netoid_h323id_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->h323id, H323ID_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_NetoidH323IdKey(xdrs, objp)
	register XDR *xdrs;
	NetoidH323IdKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_netoid_h323id_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_netoid_tg_key(xdrs, objp)
	register XDR *xdrs;
	netoid_tg_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->tg, PHONE_NUM_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_NetoidTgKey(xdrs, objp)
	register XDR *xdrs;
	NetoidTgKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_netoid_tg_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_netoid_sipuri_key(xdrs, objp)
	register XDR *xdrs;
	netoid_sipuri_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->uri, SIPURL_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_NetoidUriKey(xdrs, objp)
	register XDR *xdrs;
	NetoidUriKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_netoid_sipuri_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_netoid_crid_key(xdrs, objp)
	register XDR *xdrs;
	netoid_crid_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_u_int(xdrs, &objp->crId))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_NetoidCrIdKey(xdrs, objp)
	register XDR *xdrs;
	NetoidCrIdKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_netoid_crid_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_realm_ip_key(xdrs, objp)
	register XDR *xdrs;
	realm_ip_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_u_long(xdrs, &objp->ipaddress))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->realmId))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_RealmIP(xdrs, objp)
	register XDR *xdrs;
	RealmIP *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_realm_ip_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_subnet_ip_key(xdrs, objp)
	register XDR *xdrs;
	subnet_ip_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_u_long(xdrs, &objp->subnetip))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->mask))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Subnet(xdrs, objp)
	register XDR *xdrs;
	Subnet *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_subnet_ip_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vpn_key(xdrs, objp)
	register XDR *xdrs;
	vpn_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->vpnName, VPNS_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_VpnKey(xdrs, objp)
	register XDR *xdrs;
	VpnKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_vpn_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vpn_group_key(xdrs, objp)
	register XDR *xdrs;
	vpn_group_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->vpnGroup, VPN_GROUP_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_VpnGroupKey(xdrs, objp)
	register XDR *xdrs;
	VpnGroupKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_vpn_group_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_trigger_key(xdrs, objp)
	register XDR *xdrs;
	trigger_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->name, TRIGGER_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_TriggerKey(xdrs, objp)
	register XDR *xdrs;
	TriggerKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_trigger_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_igrp_key(xdrs, objp)
	register XDR *xdrs;
	igrp_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->igrpNameKey, IGRP_NAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_IgrpKey(xdrs, objp)
	register XDR *xdrs;
	IgrpKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_igrp_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_realm_subnet_key(xdrs, objp)
	register XDR *xdrs;
	realm_subnet_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_u_long(xdrs, &objp->subnetip))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->mask))
		return (FALSE);
	if (!xdr_u_long(xdrs, &objp->realmId))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_RealmSubnet(xdrs, objp)
	register XDR *xdrs;
	RealmSubnet *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_realm_subnet_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_realm_id_key(xdrs, objp)
	register XDR *xdrs;
	realm_id_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_u_long(xdrs, &objp->realmId))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_RealmIdKey(xdrs, objp)
	register XDR *xdrs;
	RealmIdKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_realm_id_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_rsa_id_key(xdrs, objp)
	register XDR *xdrs;
	rsa_id_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_u_long(xdrs, &objp->rsa))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_RsaKey(xdrs, objp)
	register XDR *xdrs;
	RsaKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_rsa_id_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_crname_key(xdrs, objp)
	register XDR *xdrs;
	crname_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->crname, CALLPLAN_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_VpnRouteKey(xdrs, objp)
	register XDR *xdrs;
	VpnRouteKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_crname_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CallPlanRouteKey(xdrs, objp)
	register XDR *xdrs;
	CallPlanRouteKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_crname_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_RouteKey(xdrs, objp)
	register XDR *xdrs;
	RouteKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_crname_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_call_plan_key(xdrs, objp)
	register XDR *xdrs;
	call_plan_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->cpname, CALLPLAN_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CallPlanKey(xdrs, objp)
	register XDR *xdrs;
	CallPlanKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_call_plan_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_lru_key(xdrs, objp)
	register XDR *xdrs;
	lru_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_time_t(xdrs, &objp->rTime))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_LruKey(xdrs, objp)
	register XDR *xdrs;
	LruKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_lru_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cpb_key(xdrs, objp)
	register XDR *xdrs;
	cpb_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->cpname, CALLPLAN_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->crname, CALLPLAN_ATTR_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CallPlanBindKey(xdrs, objp)
	register XDR *xdrs;
	CallPlanBindKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_cpb_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_realm_key(xdrs, objp)
	register XDR *xdrs;
	realm_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_vector(xdrs, (char *)objp->realmNameKey, REALM_NAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_RealmKey(xdrs, objp)
	register XDR *xdrs;
	RealmKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_realm_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cache_key(xdrs, objp)
	register XDR *xdrs;
	cache_key *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_int(xdrs, &objp->cache))
		return (FALSE);
	switch (objp->cache) {
	case REG_CACHE:
		if (!xdr_NetoidSNKey(xdrs, &objp->cache_key_u.keyInfoEntry))
			return (FALSE);
		break;
	case IP_CACHE:
		if (!xdr_RealmIP(xdrs, &objp->cache_key_u.keyRealmIP))
			return (FALSE);
		break;
	case VPN_PHONE_CACHE:
	case PHONE_CACHE:
		if (!xdr_NetoidPhoneKey(xdrs, &objp->cache_key_u.keyPhone))
			return (FALSE);
		break;
	case EMAIL_CACHE:
		if (!xdr_NetoidEmailKey(xdrs, &objp->cache_key_u.keyEmail))
			return (FALSE);
		break;
	case GK_CACHE:
		if (!xdr_NetoidSNKey(xdrs, &objp->cache_key_u.keyGk))
			return (FALSE);
		break;
	case URI_CACHE:
		if (!xdr_NetoidUriKey(xdrs, &objp->cache_key_u.keyUri))
			return (FALSE);
		break;
	case H323ID_CACHE:
		if (!xdr_NetoidH323IdKey(xdrs, &objp->cache_key_u.keyh323Id))
			return (FALSE);
		break;
	case SUBNET_CACHE:
		if (!xdr_RealmSubnet(xdrs, &objp->cache_key_u.keyRealmSubnet))
			return (FALSE);
		break;
	case CRID_CACHE:
		if (!xdr_NetoidCrIdKey(xdrs, &objp->cache_key_u.keyCrId))
			return (FALSE);
		break;
	case TG_CACHE:
	case DTG_CACHE:
		if (!xdr_NetoidTgKey(xdrs, &objp->cache_key_u.keyTg))
			return (FALSE);
		break;
	case TRIGGER_CACHE:
		if (!xdr_TriggerEntry(xdrs, &objp->cache_key_u.keyTrigger))
			return (FALSE);
		break;
	case REALM_CACHE:
	case RSA_CACHE:
		if (!xdr_u_long(xdrs, &objp->cache_key_u.keyRealm))
			return (FALSE);
		break;
	case IGRP_CACHE:
		if (!xdr_IgrpKey(xdrs, &objp->cache_key_u.keyIgrp))
			return (FALSE);
		break;
	case VPN_CACHE:
		if (!xdr_VpnKey(xdrs, &objp->cache_key_u.keyVpn))
			return (FALSE);
		break;
	case VPNG_CACHE:
		if (!xdr_VpnGroupKey(xdrs, &objp->cache_key_u.keyVpnG))
			return (FALSE);
		break;
	case CP_CACHE:
		if (!xdr_CallPlanRouteKey(xdrs, &objp->cache_key_u.keyCp))
			return (FALSE);
		break;
	case CPB_CACHE:
	case CPBCR_CACHE:
	case CPBCP_CACHE:
		if (!xdr_CallPlanBindKey(xdrs, &objp->cache_key_u.keyCpb))
			return (FALSE);
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_CacheKey(xdrs, objp)
	register XDR *xdrs;
	CacheKey *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_cache_key(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cache_entry(xdrs, objp)
	register XDR *xdrs;
	cache_entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_int(xdrs, &objp->cache))
		return (FALSE);
	switch (objp->cache) {
	case REG_CACHE:
	case IP_CACHE:
	case VPN_PHONE_CACHE:
	case PHONE_CACHE:
	case EMAIL_CACHE:
	case URI_CACHE:
	case H323ID_CACHE:
	case SUBNET_CACHE:
	case CRID_CACHE:
	case TG_CACHE:
		if (!xdr_CacheTableInfo(xdrs, &objp->cache_entry_u.cacheInfoEntry))
			return (FALSE);
		break;
	case REALM_CACHE:
	case RSA_CACHE:
		if (!xdr_CacheRealmEntry(xdrs, &objp->cache_entry_u.cacheRealmEntry))
			return (FALSE);
		break;
	case IGRP_CACHE:
		if (!xdr_CacheIgrpInfo(xdrs, &objp->cache_entry_u.cacheIgrpEntry))
			return (FALSE);
		break;
	case GK_CACHE:
		if (!xdr_CacheGkInfo(xdrs, &objp->cache_entry_u.cacheGkEntry))
			return (FALSE);
		break;
	case TRIGGER_CACHE:
		if (!xdr_CacheTriggerEntry(xdrs, &objp->cache_entry_u.cacheTriggerEntry))
			return (FALSE);
		break;
	case VPN_CACHE:
		if (!xdr_CacheVpnEntry(xdrs, &objp->cache_entry_u.cacheVpnEntry))
			return (FALSE);
		break;
	case VPNG_CACHE:
		if (!xdr_CacheVpnGEntry(xdrs, &objp->cache_entry_u.cacheVpnGEntry))
			return (FALSE);
		break;
	case CP_CACHE:
		if (!xdr_CacheCPEntry(xdrs, &objp->cache_entry_u.cacheCPEntry))
			return (FALSE);
		break;
	case CPB_CACHE:
	case CPBCR_CACHE:
	case CPBCP_CACHE:
		if (!xdr_CacheCPBEntry(xdrs, &objp->cache_entry_u.cacheCPBEntry))
			return (FALSE);
		break;
	case CACHE_IGNORE:
		if (!xdr_u_int(xdrs, &objp->cache_entry_u.foo))
			return (FALSE);
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_CacheEntryGeneric(xdrs, objp)
	register XDR *xdrs;
	CacheEntryGeneric *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_cache_entry(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_netoid_var_a(xdrs, objp)
	register XDR *xdrs;
	netoid_var_a *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->infoEntryVar_a.infoEntryVar_a_val, (u_int *) &objp->infoEntryVar_a.infoEntryVar_a_len, ~0,
		sizeof (NetoidInfoEntry), (xdrproc_t) xdr_NetoidInfoEntry))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_NetoidVarArr(xdrs, objp)
	register XDR *xdrs;
	NetoidVarArr *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_netoid_var_a(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheTableInfo_va(xdrs, objp)
	register XDR *xdrs;
	CacheTableInfo_va *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->CacheTableInfo_va_val, (u_int *) &objp->CacheTableInfo_va_len, ~0,
		sizeof (CacheTableInfo), (xdrproc_t) xdr_CacheTableInfo))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheGkInfo_va(xdrs, objp)
	register XDR *xdrs;
	CacheGkInfo_va *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->CacheGkInfo_va_val, (u_int *) &objp->CacheGkInfo_va_len, ~0,
		sizeof (CacheGkInfo), (xdrproc_t) xdr_CacheGkInfo))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheTriggerEntry_va(xdrs, objp)
	register XDR *xdrs;
	CacheTriggerEntry_va *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->CacheTriggerEntry_va_val, (u_int *) &objp->CacheTriggerEntry_va_len, ~0,
		sizeof (CacheTriggerEntry), (xdrproc_t) xdr_CacheTriggerEntry))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheRealmEntry_va(xdrs, objp)
	register XDR *xdrs;
	CacheRealmEntry_va *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->CacheRealmEntry_va_val, (u_int *) &objp->CacheRealmEntry_va_len, ~0,
		sizeof (CacheRealmEntry), (xdrproc_t) xdr_CacheRealmEntry))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheIgrpInfo_va(xdrs, objp)
	register XDR *xdrs;
	CacheIgrpInfo_va *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->CacheIgrpInfo_va_val, (u_int *) &objp->CacheIgrpInfo_va_len, ~0,
		sizeof (CacheIgrpInfo), (xdrproc_t) xdr_CacheIgrpInfo))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheVpnEntry_va(xdrs, objp)
	register XDR *xdrs;
	CacheVpnEntry_va *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->CacheVpnEntry_va_val, (u_int *) &objp->CacheVpnEntry_va_len, ~0,
		sizeof (CacheVpnEntry), (xdrproc_t) xdr_CacheVpnEntry))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheVpnGEntry_va(xdrs, objp)
	register XDR *xdrs;
	CacheVpnGEntry_va *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->CacheVpnGEntry_va_val, (u_int *) &objp->CacheVpnGEntry_va_len, ~0,
		sizeof (CacheVpnGEntry), (xdrproc_t) xdr_CacheVpnGEntry))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheCPBEntry_va(xdrs, objp)
	register XDR *xdrs;
	CacheCPBEntry_va *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->CacheCPBEntry_va_val, (u_int *) &objp->CacheCPBEntry_va_len, ~0,
		sizeof (CacheCPBEntry), (xdrproc_t) xdr_CacheCPBEntry))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_CacheCREntry_va(xdrs, objp)
	register XDR *xdrs;
	CacheCREntry_va *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->CacheCREntry_va_val, (u_int *) &objp->CacheCREntry_va_len, ~0,
		sizeof (CacheRouteEntry), (xdrproc_t) xdr_CacheRouteEntry))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_char_va(xdrs, objp)
	register XDR *xdrs;
	char_va *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->char_va_val, (u_int *) &objp->char_va_len, 128,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_str_va(xdrs, objp)
	register XDR *xdrs;
	str_va *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->str_va_val, (u_int *) &objp->str_va_len, 128,
		sizeof (char_va), (xdrproc_t) xdr_char_va))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_get_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_get_1_argument *objp;
{

	if (!xdr_int(xdrs, &objp->cacheType))
		return (FALSE);
	if (!xdr_CacheKey(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_getnext_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_getnext_1_argument *objp;
{

	if (!xdr_int(xdrs, &objp->cacheType))
		return (FALSE);
	if (!xdr_CacheKey(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_insert_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_insert_1_argument *objp;
{

	if (!xdr_int(xdrs, &objp->cacheType))
		return (FALSE);
	if (!xdr_CacheEntryGeneric(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_delete_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_delete_1_argument *objp;
{

	if (!xdr_int(xdrs, &objp->cacheType))
		return (FALSE);
	if (!xdr_CacheEntryGeneric(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_remove_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_remove_1_argument *objp;
{

	if (!xdr_int(xdrs, &objp->cacheType))
		return (FALSE);
	if (!xdr_CacheEntryGeneric(xdrs, &objp->data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_handle_iedge_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_handle_iedge_1_argument *objp;
{

	if (!xdr_pointer(xdrs, (char **)&objp->netInfo, sizeof (NetoidInfoEntry), (xdrproc_t) xdr_NetoidInfoEntry))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->cacheType))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->op))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_handle_mem_age_iedges_in_vpngs_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_handle_mem_age_iedges_in_vpngs_1_argument *objp;
{

	if (!xdr_string(xdrs, &objp->vpng1, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->vpng2, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_handle_vpn_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_handle_vpn_1_argument *objp;
{

	if (!xdr_pointer(xdrs, (char **)&objp->vpnEntry, sizeof (VpnEntry), (xdrproc_t) xdr_VpnEntry))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->op))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_handle_vpng_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_handle_vpng_1_argument *objp;
{

	if (!xdr_pointer(xdrs, (char **)&objp->vpnGroupEntry, sizeof (VpnGroupEntry), (xdrproc_t) xdr_VpnGroupEntry))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->op))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_handle_cr_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_handle_cr_1_argument *objp;
{

	if (!xdr_pointer(xdrs, (char **)&objp->routeEntry, sizeof (VpnRouteEntry), (xdrproc_t) xdr_VpnRouteEntry))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->op))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_handle_cp_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_handle_cp_1_argument *objp;
{

	if (!xdr_pointer(xdrs, (char **)&objp->cpEntry, sizeof (CallPlanEntry), (xdrproc_t) xdr_CallPlanEntry))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->op))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_handle_cpb_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_handle_cpb_1_argument *objp;
{

	if (!xdr_pointer(xdrs, (char **)&objp->cpbEntry, sizeof (CallPlanBindEntry), (xdrproc_t) xdr_CallPlanBindEntry))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->op))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_handle_igrp_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_handle_igrp_1_argument *objp;
{

	if (!xdr_pointer(xdrs, (char **)&objp->igrpEntry, sizeof (IgrpInfo), (xdrproc_t) xdr_IgrpInfo))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->op))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_handle_realm_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_handle_realm_1_argument *objp;
{

	if (!xdr_pointer(xdrs, (char **)&objp->rmEntry, sizeof (RealmEntry), (xdrproc_t) xdr_RealmEntry))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->op))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_cache_handle_trigger_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_cache_handle_trigger_1_argument *objp;
{

	if (!xdr_pointer(xdrs, (char **)&objp->tgEntry, sizeof (TriggerEntry), (xdrproc_t) xdr_TriggerEntry))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->op))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_handle_check_rsa_dup_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_handle_check_rsa_dup_1_argument *objp;
{

	if (!xdr_pointer(xdrs, (char **)&objp->new, sizeof (RealmEntry), (xdrproc_t) xdr_RealmEntry))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->old, sizeof (RealmEntry), (xdrproc_t) xdr_RealmEntry))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_handle_igrp_add_calls_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_handle_igrp_add_calls_1_argument *objp;
{

	if (!xdr_string(xdrs, &objp->igrpname, ~0))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->incalls))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->outcalls))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->totalcalls))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cli_handle_igrp_delete_calls_1_argument(xdrs, objp)
	register XDR *xdrs;
	cli_handle_igrp_delete_calls_1_argument *objp;
{

	if (!xdr_string(xdrs, &objp->igrpname, ~0))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->incalls))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->outcalls))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->totalcalls))
		return (FALSE);
	return (TRUE);
}
