/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "scmrpcprog.h"
#ifndef _KERNEL
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */
#endif /* !_KERNEL */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
scm_updatecall_1(CallHandle *arg1, char *bEvP, char *nEvP, CLIENT *clnt)
{
	scm_updatecall_1_argument arg;
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	arg.arg1 = arg1;
	arg.bEvP = bEvP;
	arg.nEvP = nEvP;
	if (clnt_call(clnt, SCM_UPDATECALL,
		(xdrproc_t) xdr_scm_updatecall_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
scm_deletecall_1(ScmrpcCallid *arg1, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, SCM_DELETECALL,
		(xdrproc_t) xdr_ScmrpcCallid, (caddr_t) arg1,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

int *
scm_heartbeat_1(u_long arg1, u_long arg2, CLIENT *clnt)
{
	scm_heartbeat_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call(clnt, SCM_HEARTBEAT,
		(xdrproc_t) xdr_scm_heartbeat_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
scm_send_opq_1(OpqBuff *arg1, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, SCM_SEND_OPQ,
		(xdrproc_t) xdr_OpqBuff, (caddr_t) arg1,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}
