#include "gis.h"

#include "sipkey.h"
#include "sipcall.h"
#include "siptrans.h"

#include "include/tsm.h"
#include <malloc.h>

extern int SipGlbTimer(SipTrans *siptran);
 
/* For non-200 final response, ack is generated by TSM (not by CSM) and termination timer is
 * started following ack;
 * For 200 final response, ack is generated by CSM if SDP is needed in ack. Otherwise ack is
 * generated by TSM. And termination timer is started after ack 
 * is received from CSM or generated by TSM and transmitted.
 * Action routine "SipSendAck" checks whether ACK message has been cooked up before sending.
 * Action routine "SipInviteClientTermTimer" checks whether ACK message has been cooked up before
 * starting the actual timer
 */

SipTranSMEntry 
SipInviteSM_Client[SipInviteSM_ClientMaxStates][SipInviteSM_ClientMaxEvents]=
{
	/* SipInvite_ClientIdle */
	{
		/* SipRequestFrCSM */ 
		{
			SipInvite_ClientCalling,
			{SipSendRequest, SipInviteClientReTxTimer},
		},
		/* SipInviteClientReTxExpire */
		{
			SipInvite_ClientIdle,
			{SipNop},
		},
		/* SipInvite7Sent */
		{
			SipInvite_ClientIdle,
			{SipNop},
		},
		/* Sip1xxFrNet */
		{
			SipInvite_ClientIdle,
			{SipNop},
		},
		/* SipFinalFrNet */
		{
			SipInvite_ClientIdle,
			{SipNop},
		},
		/* SipAckFrCSM */
		{
			SipInvite_ClientIdle,
			{SipNop},
		},
		/* SipInviteClientTermExpire */
		{
			SipInvite_ClientIdle,
			{SipNop},
		},
	},

	/* SipInvite_ClientCalling */
	{
		/* SipRequestFrCSM */ 
		{
			SipInvite_ClientCalling,
			{SipNop},
		},
		/* SipInviteClientReTxExpire */
		{
			SipInvite_ClientCalling,
			{SipSendRequest, SipInviteClientReTxTimer},
		},
		/* SipInvite7Sent */
		{
			SipInvite_ClientCompleted,
			{SipErrorCSM2, SipGlbTimer},
		},
		/* Sip1xxFrNet */
		{
			SipInvite_ClientProc,
			{SipRespCSM2, SipDeleteTimer},
		},
		/* SipFinalFrNet */
		{
			SipInvite_ClientConfirmed,
			{SipSendAck, SipRespCSM2, SipDeleteTimer, SipInviteClientTermTimer},
		},
		/* SipAckFrCSM */
		{
			SipInvite_ClientCalling,
			{SipNop},
		},
		/* SipInviteClientTermExpire */
		{
			SipInvite_ClientCalling,
			{SipNop},
		},
	},

	/* SipInvite_ClientProc */
	{
		/* SipRequestFrCSM */ 
		{
			SipInvite_ClientProc,
			{SipNop},
		},
		/* SipInviteClientReTxExpire */
		{
			SipInvite_ClientProc,
			{SipNop},
		},
		/* SipInvite7Sent */
		{
			SipInvite_ClientProc,
			{SipGlbTimer},
		},
		/* Sip1xxFrNet */
		{
			SipInvite_ClientProc,
			{SipRespCSM2},
		},
		/* SipFinalFrNet */
		{
			SipInvite_ClientConfirmed,
			{SipSendAck, SipRespCSM2, SipInviteClientTermTimer},
		},
		/* SipAckFrCSM */
		{
			SipInvite_ClientProc,
			{SipNop},
		},
		/* SipInviteClientTermExpire */
		{
			SipInvite_ClientProc,
			{SipNop},
		},
	},

	/* SipInvite_ClientConfirmed */
	{
		/* SipRequestFrCSM */ 
		{
			SipInvite_ClientConfirmed,
			{SipNop},
		},
		/* SipInviteClientReTxExpire */
		{
			SipInvite_ClientConfirmed,
			{SipNop},
		},
		/* SipInvite7Sent */
		{
			SipInvite_ClientConfirmed,
			{SipNop},
		},
		/* Sip1xxFrNet */
		{
			SipInvite_ClientConfirmed,
			{SipRespCSM2},
		},
		/* SipFinalFrNet */
		{
			SipInvite_ClientConfirmed,
			{SipSendAck, SipRespCSM2},
		},
		/* SipAckFrCSM */
		{
			SipInvite_ClientConfirmed,
			{SipSendAck, SipInviteClientTermTimer},
		},
		/* SipInviteClientTermExpire */
		{
			SipInvite_ClientCompleted,
			{SipRemoveTSM},
		}
	},

	/* SipInvite_ClientCompleted */
	{
		/* SipRequestFrCSM */ 
		{
			SipInvite_ClientCalling,
			{SipNop},
		},
		/* SipInviteClientReTxExpire */
		{
			SipInvite_ClientCalling,
			{SipNop},
		},
		/* SipInvite7Sent */
		{
			SipInvite_ClientCompleted,
			{SipRemoveTSM},
		},
		/* Sip1xxFrNet */
		{
			SipInvite_ClientProc,
			{SipNop},
		},
		/* SipFinalFrNet */
		{
			SipInvite_ClientConfirmed,
			{SipNop},
		},
		/* SipAckFrCSM */
		{
			SipInvite_ClientCalling,
			{SipNop},
		},
		/* SipInviteClientTermExpire */
		{
			SipInvite_ClientCalling,
			{SipNop},
		},
	},

};

char SipInviteSM_ClientStates[][32]={
	"SipInvite_ClientIdle", 
	"SipInvite_ClientCalling", 
	"SipInvite_ClientProc",
	"SipInvite_ClientConfirmed", 
	"SipInvite_ClientCompleted",
};

char SipInviteSM_ClientEvents[][32]={
	"SipRequestFrCSM", 
	"SipInviteClientReTxExpire", 
	"SipInvite7Sent",
	"Sip1xxFrNet", 
	"SipFinalFrNet", 
	"SipAckFrCSM", 
	"SipInviteClientTermExpire",
};

