# Makefile for NexTest QMTest extensions
# $Id: Makefile,v 1.2 2004/05/28 19:48:13 slowrey Exp $
#
# THIS FILE IS NOT USED
#
QM_EXT = /opt/nextest/lib/qmext

INSTALL_FILES = call.py classes.qmc control.py endpoint.py benchmark.py

install:
	for file in $(INSTALL_FILES)
	install -m 644 $file $(QM_EXT)
