/*
 *
 * All the stack headers are included in this file
 *
 */

#ifndef __STACK_HEADERS_H__
#define __STACK_HEADERS_H__

/* This header file will be generated by the configure script */
#include "stack_config.h"

/* Core stack files*/
#include "sipcommon.h"
#include "sipstruct.h"
#include "bcpt.h"
#include "entity.h"
#include "general.h"
#include "header.h"
#include "sipvalidate.h"
#include "portlayer.h"
#include "request.h"
#include "response.h"
#include "rpr.h"
#include "rprfree.h"
#include "rprinit.h"
#include "rprinternal.h"
#include "sdp.h"
#include "sdpdecode.h"
#include "sdpstring.h"
#include "sipbcptfree.h"
#include "sipbcptinit.h"
#include "sipbcptinternal.h"
#include "sipclone.h"
#include "sipcloneintrnl.h"
#include "sipdecode.h"
#include "sipdecodeintrnl.h"
#include "sipformmessage.h"
#include "sipfree.h"
#include "siphash.h"
#include "sipinit.h"
#include "sipinternal.h"
#include "siplist.h"
#include "sipparserclone.h"
#include "sipparserinc.h"
#include "sipsendmessage.h"
#include "sipstatistics.h"
#include "sipstring.h"
#include "sipstringintrnl.h"
#include "siptimer.h"
#include "siptrace.h"

#ifdef SIP_SERIALIZE
#include "byteordering.h"
#include "serialize.h"
#include "serializeHeaders.h"
#endif

#ifdef SIP_CCP
#include "ccp.h"
#include "ccpfree.h"
#include "ccpinit.h"
#include "ccpinternal.h"
#include "ccpstruct.h"
#endif

#ifdef SIP_DCS
#include "dcs.h"
#include "dcsclone.h"
#include "dcsdecode.h"
#include "dcsformmessage.h"
#include "dcsfree.h"
#include "dcsinit.h"
#include "dcsintrnl.h"
#include "dcsstring.h"
#endif

#ifdef SIP_IMPP
#include "impp.h"
#include "imppfree.h"
#include "imppinit.h"
#include "imppinternal.h"
#include "imppstruct.h"
#include "imurldecodeintrnl.h"
#endif

#ifdef SIP_MWI
#include "mesgsummary.h"
#endif

#ifdef SIP_TXN_LAYER
#include "siptxnstruct.h"
#include "siptxntimer.h"
#include "txnclone.h"
#include "txndecode.h"
#include "txndecodeintrnl.h"
#include "txnfree.h"
#include "txninit.h"
#include "txnmidway.h"
#endif

#ifdef SIP_TEL
#include "telapi.h"
#include "teldecodeintrnl.h"
#include "telfree.h"
#include "telinit.h"
#include "telintrnl.h"
#include "telstruct.h"
#endif

#endif

