/* Stack flags enabled by the user
 This is a generated file, please do not edit this file */

#ifndef __STACK_CONFIG_H__
#define __STACK_CONFIG_H__

#define SIP_SOLARIS
#define ANSI_PROTO
#undef SIP_TXN_LAYER
#undef SIP_MIB
#undef SIP_ATM
#undef SIP_PINT
#undef SIP_IMPP
#undef SIP_MWI
#undef SIP_TEL
#undef SIP_PRES
#undef SIP_SECURITY
#define SIP_SESSIONTIMER
#undef SIP_CCP
#define SIP_DCS
#define SIP_PRIVACY
#define SIP_3GPP
#undef SIP_CONGEST
#undef SIP_CONF
#define SIP_BY_REFERENCE
#undef SIP_NO_CALLBACK
#define SIP_THREAD_SAFE
#define SIP_TRACE
#define SIP_STATISTICS
#undef SIP_DEBUG
#undef SIP_FNDEBUG
#define SIP_ERROR
#undef SIP_SELECTIVE_PARSE
#define SIP_MSGBUFFER_CHECK
#undef SIP_INCOMPLETE_MSG_CHECK
#undef SIP_OVERRIDE_SNPRINTF
#undef SIP_NOFLEXRECOVERY
#undef SIP_NO_FILESYS_DEP
#undef SIP_RETRANSCALLBACK
#undef SIP_LOCKEDREFCOUNT

#endif

