/* This file was generated by RADVISION ASN.1 Compiler */
/* This is a compilation of : common.asn */

#ifndef _common_ASN_H
#define _common_ASN_H

#ifdef __cplusplus
extern "C" {
#endif

unsigned char* commonasnGetSyntax(void);

#ifdef __cplusplus
#define __ENUM enum
#define __NAME1 _common
#define __NAME2 
#else
#define __ENUM typedef enum
#define __NAME1 
#define __NAME2 _common
#endif


__ENUM __NAME1 {
  _common_CCConfig = 0,
  _common_CDConfig = 10,
  _common_CHConfig = 20,
  _common_CIConfig = 30,
  _common_COConfig = 40,
  _common_CPConfig = 50,
  _common_CTConfig = 60,
  _common_CWConfig = 70,
  _common_H450SystemConfiguration = 80,
  _common_MWIConfig = 105,
  _common_SystemConfiguration = 116,
  _common_allocations = 137,
  _common_allocations_32 = 150,
  _common_allocations_5 = 166,
  _common_c_default_cipl = 181,
  _common_c_default_cipl_80 = 197,
  _common_callPropertyMode = 216,
  _common_callPropertyMode_26 = 234,
  _common_canRetainService = 255,
  _common_canRetainService_70 = 273,
  _common_cct1 = 294,
  _common_cct1_67 = 300,
  _common_cct2Busy = 309,
  _common_cct2Busy_68 = 319,
  _common_cct2NoResponse = 332,
  _common_cct2NoResponse_69 = 348,
  _common_cdt1 = 367,
  _common_cdt2 = 373,
  _common_cdt3 = 379,
  _common_cdt4 = 385,
  _common_cdt5 = 391,
  _common_chanDescs = 397,
  _common_channels = 408,
  _common_cht1 = 418,
  _common_cht2 = 424,
  _common_cicl = 430,
  _common_cidAssociate = 436,
  _common_cipl = 450,
  _common_cit1 = 456,
  _common_cit2 = 462,
  _common_cit3 = 468,
  _common_cit4 = 474,
  _common_cit5 = 480,
  _common_cit6 = 486,
  _common_cit6_77 = 492,
  _common_classReference = 501,
  _common_constrainingField = 517,
  _common_containerOfObjectSets = 536,
  _common_containerOfObjects = 559,
  _common_containerOfTypes = 579,
  _common_containerOfValues = 597,
  _common_copySingleMessages = 616,
  _common_cpt1 = 636,
  _common_cpt10 = 642,
  _common_cpt2 = 649,
  _common_cpt3 = 655,
  _common_cpt4 = 661,
  _common_cpt5 = 667,
  _common_cpt6 = 673,
  _common_cpt7 = 679,
  _common_cpt8 = 685,
  _common_cpt9 = 691,
  _common_ctt1 = 697,
  _common_ctt2 = 703,
  _common_ctt3 = 709,
  _common_ctt4 = 715,
  _common_deleteSingleMessages = 721,
  _common_delimiter = 743,
  _common_delimiter_4 = 754,
  _common_doNotUseProperty = 767,
  _common_fieldOfClassReference = 785,
  _common_fieldOfEnumerated = 808,
  _common_fieldOfObjectReference = 827,
  _common_fieldReference = 851,
  _common_fullProperty = 867,
  _common_imports = 881,
  _common_importsArray = 890,
  _common_indicateCalling = 904,
  _common_localIPAddress = 921,
  _common_localIPAddress_23 = 937,
  _common_manualStart = 956,
  _common_maxBuffSize = 969,
  _common_maxBuffSize_17 = 982,
  _common_maxCalls = 998,
  _common_maxChannels = 1008,
  _common_maxPoolSizeInKB = 1021,
  _common_maxPoolSizeInKB_18 = 1038,
  _common_maxProcs = 1058,
  _common_maxRasInTransactions = 1068,
  _common_maxRasOutTransactions = 1090,
  _common_maxServices = 1113,
  _common_maxServices_40 = 1126,
  _common_messages = 1142,
  _common_module = 1152,
  _common_mwit1 = 1160,
  _common_mwit2 = 1167,
  _common_nameChans = 1174,
  _common_objectArray = 1185,
  _common_objectReference = 1198,
  _common_objectSetArray = 1215,
  _common_objectSetElement = 1231,
  _common_objectSetReference = 1249,
  _common_pdlName = 1269,
  _common_pdlName_31 = 1278,
  _common_portFrom = 1290,
  _common_portTo = 1300,
  _common_protocols = 1308,
  _common_silentMonitorInd = 1319,
  _common_silentMonitorInd_81 = 1337,
  _common_tcw = 1358,
  _common_tpktChans = 1363,
  _common_tpktNoBuffers = 1374,
  _common_typeArray = 1389,
  _common_typeFromConstraint = 1400,
  _common_typeReference = 1420,
  _common_udpChans = 1435,
  _common_valueNode = 1445,
  _common_valueTree = 1456,
  _common_values = 1467,
  _common_vtNodeCount = 1475,
  _common_vtPoolSize = 1488,
  _common_withSyntaxElement = 1500} __NAME2;


#undef __NAME1
#undef __NAME2
#undef __ENUM

#define _common(a) _common_##a,
#define __common(a) _common_##a

#ifdef __cplusplus
}
#endif

#endif

