# $Id: bashrc,v 1.11 2005/11/19 15:41:43 dchahal Exp $
#
#
export QMTEST_DB_PATH=/var/opt/nextest/tdb
export QMTEST_CLASS_PATH=/opt/nextest/lib/qmext
export CLASSPATH=/opt/nextest/lib/java:/opt/nextest/lib/java/jServer.jar
export PATH=$PATH:/sbin
export PATH=$PATH:/usr/lib/SunJava2/jre/bin
export PATH=$PATH:/opt/nextest/bin
export PATH=$PATH:/usr/local/nxgen/bin
export PYTHONPATH=/opt/nextest/lib/python2.7/site-packages

PS1='\u@\h \W $ '

alias qmt='qmtest gui --no-browser --address=CHANGE_ME --port=8787'
alias dbgon='export NEXTEST_DEBUG=1'
alias dbgoff='unset NEXTEST_DEBUG'
