#!/usr/bin/perl


##
## gather.pl
##

$mProgName = "gather.pl";
$mVersion  = "v0.1, 11/04/2002";

$NexToneEtcPath = "/usr/local/nextone/etc";

$PktCount = 15;
$SaveFile = "/tmp/ether.out";
$EtherealCommand = "/usr/local/bin/tethereal -c $PktCount -w $SaveFile";

$NetstatCommand = "netstat -an | grep EST | grep 1720 | wc -l";

$GisPidCommand = "pgrep -x gis";

$GcoreCommand = "gcore $GisPidCommand";

$SarCPUCommand = "sar 2 1";

$SarMemCommand = "sar -r 2 1";



$res = system ($EtherealCommand);
if ($res)
{
	print "Error in $EtherealCommand\n";
}


$NetstatResult = `$NetstatCommand`;
chop $NetstatResult;

$GisPidResult = `$GisPidCommand`;
chop $GisPidResult;

if ($GisPidResult)
{
	$GcoreCommand = "gcore $GisPidResult";
	$res = system ($GcoreCommand);
	if ($res)
	{
		print "Error in $GcoreCommand\n";
	}
}

$SarCPUResult = `$SarCPUCommand`;

$SarMemResult = `$SarMemCommand`;


## Gather other information

	($day, $month) = (localtime)[3,4];
	$month += 1;	## Convert from Unix month to regular month
	$dtime = sprintf("%2d:%2d", (localtime)[2,1]);
	$hostname = `hostname`;
	chop $hostname;

	$date = `date`;
	chop $date;


## Now put it all in an e-mail.



$message = <<eEOF;

System information from $hostname on $month/$day, $dtime

Result of command:
$NetstatCommand
$NetstatResult

----------------------------------------------------------------------

Result of command:
$SarCPUCommand
$SarCPUResult

----------------------------------------------------------------------

Result of command:
$SarMemCommand
$SarMemResult

----------------------------------------------------------------------

A core file was generated by $GcoreCommand

----------------------------------------------------------------------

Enclosed is a network trace using the following tool: 
$EtherealCommand 


***********************************************************************
Message generated by $mProgName, $mVersion on $date
***********************************************************************
eEOF


	my $NotifyFile = "$NexToneEtcPath/mail.pl -s GatherReport -a $SaveFile tout";
	my $MessageFile = "tout";
	open (T, "> $MessageFile") or die "unable to open file";

	print T "$message\n";

	close (T);

	system ($NotifyFile);



